name: netflix
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  google_fonts: ^3.0.1
  json_annotation: ^4.6.0
  json_serializable: ^6.3.0
  video_player: ^2.4.5

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.4

flutter:

  uses-material-design: true

  assets:
    - assets/images/
