name: netflix
description: A new Flutter project.

publish_to: 'none'

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  bordered_text: ^2.0.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  injectable: ^1.5.3
  json_annotation: ^4.4.0
  json_serializable: ^6.1.5
  video_player: ^2.4.5

dev_dependencies:
  build_runner: ^2.1.8
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter
  freezed: ^1.1.1
  injectable_generator: ^1.5.3

flutter:

  uses-material-design: true

  assets:
    - assets/images/
